[package]
name = "dzieres"
version = "0.1.0"

[package.metadata]
php_version = "8.3"
php_extensions = [
    "pdo",
    "pdo_sqlite",
    "sqlite3",
    "session",
    "mbstring",
    "iconv",
    "json",
    "gd",
    "curl",
    "openssl",
    "fileinfo",
]

[dependencies]
"php/php" = "8.3"

[fs]
"/app" = "."

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"

[command.annotations.wasi]
main-args = ["-S", "0.0.0.0:8000", "-t", "/app", "/app/server.php"]
env = ["DOCUMENT_ROOT=/app", "SCRIPT_FILENAME=/app/index.php", "PORT=8000", "variables_order=EGPCS"]
